// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1kFJMHTKjV5JSUk5wRI_U4YZg001Bt8',
    appId: '1:1085200151426:web:91ed44200c62064aa2959b',
    messagingSenderId: '1085200151426',
    projectId: 'prakritisvanrakshan',
    authDomain: 'prakritisvanrakshan.firebaseapp.com',
    storageBucket: 'prakritisvanrakshan.firebasestorage.app',
    measurementId: 'G-7SCDJBV000',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSrJ7frUG4a23p8YPCyB212O60xRsbftM',
    appId: '1:1085200151426:android:598fe2775ee77cd0a2959b',
    messagingSenderId: '1085200151426',
    projectId: 'prakritisvanrakshan',
    storageBucket: 'prakritisvanrakshan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9I5F9Imk6VIGRx2YAogtee5oLx-MAMsU',
    appId: '1:1085200151426:ios:8ebfdff099d273bca2959b',
    messagingSenderId: '1085200151426',
    projectId: 'prakritisvanrakshan',
    storageBucket: 'prakritisvanrakshan.firebasestorage.app',
    iosBundleId: 'com.example.prakritiSvanrakshan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9I5F9Imk6VIGRx2YAogtee5oLx-MAMsU',
    appId: '1:1085200151426:ios:8ebfdff099d273bca2959b',
    messagingSenderId: '1085200151426',
    projectId: 'prakritisvanrakshan',
    storageBucket: 'prakritisvanrakshan.firebasestorage.app',
    iosBundleId: 'com.example.prakritiSvanrakshan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv1kFJMHTKjV5JSUk5wRI_U4YZg001Bt8',
    appId: '1:1085200151426:web:2eb78a253530a2ffa2959b',
    messagingSenderId: '1085200151426',
    projectId: 'prakritisvanrakshan',
    authDomain: 'prakritisvanrakshan.firebaseapp.com',
    storageBucket: 'prakritisvanrakshan.firebasestorage.app',
    measurementId: 'G-09CG93DKP5',
  );
}
